name: automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
jobs:
  automerge:
    runs-on: [self-hosted, linux]
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@fc8281547d24638fac1e4149bbde710cced773d1"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_RETRIES: "99999999999999"
          MERGE_RETRY_SLEEP: "60000"
          UPDATE_RETRIES: "99999999999999"
          UPDATE_RETRY_SLEEP: "60000"
